# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Industry Kitchen
email: nycindustrykitchen@gmail.com
author: Walker McBain
description: > # "Traditional culinary education is expensive, bloated and focused on
    profit not outcomes. Industry Kitchen is an immersive bootcamp that
    will make you job ready at an affordable price."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/industrycooking
  - title: facebook
    url: http://facebook.com/industrycookingschool
  
